sky:
  wechat:
    appid: wx9f998f3c31f6be4b
    secret: 45bde43a76c5e5545d996379a687133f
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     host: localhost
#     port: 3306
#     database: sky_take_out
#     username: root
#     password: 123456
#   redis:
#     host: localhost
#     port: 6379
#     database: 0